-- Applied via Supabase MCP on 2026-10-07 (data only, execute_sql).
-- Main-site assistant knowledge: a full "Agents" set and a customer "How to" set, written from the product as it is.
-- The three old "Agent stores" entries are deactivated (kept for history). Editable in Admin → AI knowledge.
update phase1.ai_knowledge set is_active = false where category = 'Agent stores';

insert into phase1.ai_knowledge (category, title, content, is_active, sort_order) values
-- ───────────── AGENTS ─────────────
('Agents', 'What a DataYego agent is', 'A DataYego agent is an independent seller with their own online data store, for example yourname.datayego.com or their own domain. Agents buy every MTN, Telecel and AirtelTigo bundle at the agent price (below the public price), set their own selling prices on their store, and keep the difference on every sale. Customers pay on the agent''s store with MoMo or card; DataYego delivers the data and handles payment and support. The agent never collects cash or forwards money. Orders from an agent store have AG- references. Everything an agent gets is listed at datayego.com/agents/store.', true, 10),
('Agents', 'How to apply to be an agent', 'Go to datayego.com/agents. Sign in or create a free account, then fill the short form: full name, phone number, WhatsApp number (optional), town or area, and one line on how you will sell. Tap Send application. Applications are reviewed by the DataYego team and the decision is emailed, usually within a day. There is nothing to pay until you are approved. When approved, your store name is reserved; your store opens the moment you pay the monthly fee from your dashboard at datayego.com/agent.', true, 20),
('Agents', 'Agent fee and plans', 'Being an agent is a subscription paid from the agent dashboard: GH₵ 15.00 for 1 month, GH₵ 40.50 for 3 months (13.50 a month) or GH₵ 144.00 for 12 months (12.00 a month), plus the usual 4% checkout fee on the payment. The fee is only due after approval. Extending any time adds the new period to the end of the current one. There is one grace day after a plan ends; after that the store closes to customers and Buy data is locked until the agent renews, but the dashboard, orders, earnings and withdrawals stay available. No deposit and no float are ever required. For the current fee always use the live figure from the agent_plan tool when available.', true, 30),
('Agents', 'How agents earn and get paid', 'Profit on a sale is the customer''s price minus the agent price. It shows as Pending while the order is in progress and moves to the Available balance the moment the bundle is delivered. If an order is refunded there is no sale and no profit. Agents withdraw from Earnings & payouts once Available is GH₵ 20.00 or more; the fee is 1% (minimum GH₵ 1.00) and the money goes to the MoMo number and name saved under My store → Store details, so those must match the MoMo registration. A returned withdrawal goes back to Available with an email saying why (usually a wrong MoMo number or name).', true, 40),
('Agents', 'Agent wallet: buying data at the agent price', 'From Sell → Buy data in the dashboard, an agent buys any bundle at the agent price for any number: their own, family, or a walk-in customer who paid cash. Paying from the agent wallet has no checkout fee; the wallet is topped up with MoMo or card from the same page (the top-up itself carries the 4% fee). Paying with Paystack directly adds the 4% fee. Nothing is added to earnings on these purchases. The wallet is separate from earnings: earnings are withdrawn to MoMo, the wallet is spent on data and is not withdrawable.', true, 50),
('Agents', 'Setting prices on an agent store', 'Under Sell → Prices, every bundle shows the agent price (what the agent pays, fixed), the suggested store price, and the agent''s own price. The agent can set any price above the agent price; the difference is their profit. Their own price always wins over the suggested one. Changing a price updates the store, the checkout and Status maker images immediately. Customers only ever see the agent''s price, never the agent cost.', true, 60),
('Agents', 'Store address and your own domain', 'Every agent store is at yourname.datayego.com. The name is chosen at application and can be changed under My store → Store address; the old link keeps working for 90 days. For a real domain like mystore.com, use Domain → Connect an existing domain (one the agent already owns) or Domain → Buy a domain (search and buy a .com and other endings from the dashboard; the price for one year is shown before buying). DataYego sets up the domain, HTTPS and optionally emails from that domain. The datayego.com address keeps working as a spare.', true, 70),
('Agents', 'Templates, logo and branding', 'Under My store → Template & look an agent picks one of three complete designs, Classic, Market or Studio, each with its own home page, bundle pages, menu, footer and checkout, and can switch any time. Branding: logo, accent colour, banner, a short header name (up to 20 characters, shown in the store header), tagline, about text, opening hours, a notice bar at the top of every page, social links and a custom FAQ (My store → About & contact, FAQ). Featured bundles for the home page are chosen under My store → Featured bundles. DataYego is not shown inside an agent''s store, and shared links preview with the agent''s own name and logo.', true, 80),
('Agents', 'Status maker (WhatsApp status images)', 'Marketing → Status maker draws a ready-to-post WhatsApp status image in the store''s own template look, with the agent''s logo, link and today''s prices pulled live from the store. Options: one bundle, two bundles side by side, three bundles (small, medium, large with a Most popular tag), a promo (old price crossed out with the end date), or the whole price list for a network. The agent picks the network and bundles, previews the image in the dashboard, then taps Share to WhatsApp, Download, or Copy caption. The caption is written automatically. A good habit is posting one every morning.', true, 90),
('Agents', 'Promos, announcements, pop-ups and analytics', 'Marketing → Promos: put any bundle on promo with an end date; the store shows the old price crossed out and the promo price, and returns to normal automatically. Marketing → Announcements: post news on the store and email it to customers who have an account there. Marketing → Pop-ups: a pop-up on chosen store pages with a title, message, image and a button that opens a link, collects a form or sends a message; shows once per visit with counts of views and taps (Form submissions are listed separately). Marketing → Analytics: visits per day, orders, sales and best sellers.', true, 100),
('Agents', 'Customers, support inbox and the store assistant', 'Customers can create an account on an agent store, see their orders, track live ones and keep a wallet for faster repeat purchases. The store has a WhatsApp button and a live chat on every page (Team & support → Support buttons to turn each on or off); chat messages land in Customers → Support inbox and the agent replies from any device. The store assistant (Team & support → Store assistant) answers customers day and night from the store''s prices and details plus anything the agent adds, and hands over to the agent when needed. Customers → Orders lists every order with search, filters, grouping by day, CSV export and a WhatsApp-the-customer button; Customers → Customers lists the people who bought.', true, 110),
('Agents', 'Staff and your own agents', 'Team & support → Staff: an agent can give a sibling or shop assistant their own login to reply to customers, watch orders and check MTN numbers; staff cannot touch prices, earnings or payouts. Your agents (by invitation only): selected agents can recruit agents under their own store with their own monthly fee, application form and coupons, and earn on the sales those agents make. If an agent asks how to get this, tell them to ask the DataYego team on WhatsApp.', true, 120),
('Agents', 'MTN verification from the agent side', 'The first time an MTN number receives a bundle through DataYego, MTN holds the order and verifies the number; this can take from hours to days and is MTN''s process. The order shows Being verified by MTN in the agent''s Orders list, the customer''s money is safe, the profit shows as Pending, and the order is re-sent automatically the moment MTN clears the number; the agent does not need to do anything. Agents can check any MTN number before selling under Customers → Check MTN numbers (single or bulk) and submit new numbers for verification. Telecel and AirtelTigo have no such check.', true, 130),
('Agents', 'Agent help and where to find things', 'The agent dashboard is at datayego.com/agent. Menu: Home; Sell (Buy data, Prices); My store (Store details, Template & look, About & contact, Featured bundles, FAQ, Store address); Domain (Buy a domain, Connect an existing domain); Customers (Support inbox, Orders, Customers, Check MTN numbers); Money (Earnings & payouts); Marketing (Announcements, Promos, Status maker, Analytics, Pop-ups, Form submissions); Team & support (Store assistant, Support buttons, Staff); More (Invite & earn, Help Center). The Help Center is inside the dashboard and public at datayego.com/help/agents. Everything a store includes is at datayego.com/agents/store. For anything else, the DataYego team is on WhatsApp.', true, 140),

-- ───────────── HOW TO (customers) ─────────────
('How to', 'Buy data without an account', '1) Open datayego.com and tap Buy data (or go to datayego.com/shop). 2) Choose the network: MTN, Telecel or AirtelTigo. 3) Choose the bundle. 4) Enter the phone number that should receive the data. 5) Review and tap Pay with Paystack, then pay with MTN MoMo, Telecel Cash, AirtelTigo Money or card. A 4% checkout fee is added and shown before paying. 6) Your Order ID (YG-...) is shown and emailed to you; delivery starts automatically. No account is needed.', true, 10),
('How to', 'Buy data with an account and the DataYego wallet', 'Create a free account at datayego.com (Create account) or sign in. Top up your wallet from Wallet → Add money with MoMo or card (the top-up carries the 4% fee). Then Buy data → network → bundle → number → on Review & pay choose DataYego Wallet and tap Pay with wallet: no checkout fee on wallet payments and the order goes through in one tap. You can still choose Paystack instead. Your orders are listed under Orders in your account.', true, 20),
('How to', 'Continue an unpaid order or pay for someone''s order', 'An order that was started but not paid shows as Waiting for payment. Signed in, open Buy data → Pending orders to continue, share or cancel it. Anyone signed in can also pay for an order someone else started: Buy data → Pay for an order, enter the Order ID (YG-...), review the bundle, number and amount, and pay. The recipient number and bundle cannot be changed at payment. Unpaid orders expire on their own.', true, 30),
('How to', 'Track an order', 'Go to datayego.com/track-order and enter the Order ID (YG- for datayego.com, AG- for an agent store). The page shows the live status: waiting for payment, in progress, delivered, awaiting MTN verification, wrong network, or refunded. Signed-in customers also see their orders under Orders. Keep the Order ID from the confirmation email; support always asks for it.', true, 40),
('How to', 'Check an MTN number before buying', 'Go to datayego.com/check-mtn (also linked from the menu and the shop). Enter one or several MTN numbers. Approved means the number has received a bundle through DataYego before and orders deliver normally. Not approved means the first order will be held while MTN verifies the number, which can take days; tap Submit for verification to put it in the queue. This is free and needs no account. Only MTN numbers need this.', true, 50),
('How to', 'Data has not arrived', 'First check the order on datayego.com/track-order. Delivered: dial *138# (MTN), *126# (Telecel) or *100# (AirtelTigo) on the number that was on the order; data goes to the number entered, not the number that paid. In progress: it is on its way; do not order again. Awaiting MTN verification: the number is being verified by MTN; the order delivers automatically once cleared. Wrong network: correct the number on the Track page. Anything else, or money deducted with no order: escalate to the team with the Order ID.', true, 60),
('How to', 'Refunds', 'A customer is refunded only when the bundle genuinely cannot be delivered (for example a wrong network that cannot be corrected, or a supplier failure). The full amount goes back to the MoMo or card used, usually within hours, sometimes a few days for cards; the order then shows Refunded. Orders in progress or awaiting MTN verification are not refunded, they deliver. Refund requests are handled by the DataYego team: escalate with the Order ID.', true, 70),
('How to', 'Fees', 'Paying with Paystack (MoMo or card) adds a 4% checkout fee, shown before you pay. Paying from the DataYego wallet has no checkout fee, but topping the wallet up carries the 4% fee. Prices on the shop are the full bundle prices; there are no hidden charges.', true, 80),
('How to', 'Invite and earn', 'Signed-in customers have an invite link under their account. When someone they invite buys data, the inviter earns free data (the current reward is shown on the Invite & earn page). Share the link on WhatsApp or anywhere.', true, 90),
('How to', 'Pages and links', 'Shop: datayego.com/shop. Track an order: datayego.com/track-order. Check an MTN number: datayego.com/check-mtn. Prices by network: datayego.com/prices, /mtn-data-bundles, /telecel-data-bundles, /airteltigo-data-bundles. Become an agent: datayego.com/agents. Everything in an agent store: datayego.com/agents/store. Agent dashboard: datayego.com/agent. Agent Help Center: datayego.com/help/agents. Support: datayego.com/support. FAQ: datayego.com/faq. Always give the exact link when sending someone to a page.', true, 100);
-- ai-support edge function v28 deployed the same day: tools check_mtn_number, delivery_speed, agent_plan,
-- my_recent_orders and my_wallet (signed-in only), persona recognises customer / prospective agent / agent,
-- signed-in context passed to the model. NOTE: Gemini key is on the free tier (20 requests/day for
-- gemini-2.5-flash); owner asked to enable billing or rotate to a billed key.
