-- Phase 2: append queue_state to admin_orders_view (kept at end of column list
-- to satisfy CREATE OR REPLACE VIEW column-order rules).

CREATE OR REPLACE VIEW public.admin_orders_view AS
SELECT o.id,
   o.order_id,
   o.user_id,
   o.recipient_number,
   o.customer_name,
   o.network,
   o.bundle_size_gb,
   o.amount_ghs,
   o.cost_price_ghs,
   o.markup_percent,
   o.profit_ghs,
   o.status,
   o.payment_method,
   o.order_source,
   o.order_type,
   o.created_at,
   o.updated_at,
   o.supplier_reference,
   o.supplier_order_id,
   o.supplier_status,
   o.supplier_message,
   o.supplier_raw_response,
   o.supplier_amount,
   o.supplier_remaining_balance,
   o.supplier_timestamp,
   o.delivery_note,
   o.failure_reason,
   o.admin_notes,
   false AS is_agent_order,
   NULL::uuid AS agent_id,
   NULL::text AS agent_store_name,
   o.amount_ghs AS agent_store_price,
   NULL::numeric AS agent_base_price,
   NULL::numeric AS agent_profit,
   NULL::numeric AS datasika_profit,
   NULL::numeric AS supplier_cost_snapshot,
   false AS profit_credited,
   o.queue_state
  FROM orders o
 WHERE o.is_checkpoint = false
UNION ALL
SELECT ao.id,
   ao.order_id,
   NULL::uuid AS user_id,
   ao.customer_phone AS recipient_number,
   ao.customer_name,
   ao.network,
   ao.bundle_size_gb,
   ao.agent_selling_price AS amount_ghs,
   ao.agent_cost_price AS cost_price_ghs,
   NULL::numeric AS markup_percent,
   COALESCE(ao.agent_profit_at_purchase, ao.profit_ghs) AS profit_ghs,
   ao.status,
   ao.payment_method,
   ao.order_source,
   'standard'::text AS order_type,
   ao.created_at,
   ao.updated_at,
   ao.supplier_reference,
   ao.supplier_order_id,
   ao.supplier_status,
   ao.supplier_message,
   ao.supplier_raw_response,
   NULL::numeric AS supplier_amount,
   NULL::numeric AS supplier_remaining_balance,
   NULL::timestamp with time zone AS supplier_timestamp,
   NULL::text AS delivery_note,
   ao.failure_reason,
   NULL::text AS admin_notes,
   true AS is_agent_order,
   ao.agent_id,
   a.store_name AS agent_store_name,
   COALESCE(ao.agent_store_price_at_purchase, ao.agent_selling_price) AS agent_store_price,
   ao.agent_base_price_at_purchase AS agent_base_price,
   ao.agent_profit_at_purchase AS agent_profit,
   ao.datasika_profit_at_purchase AS datasika_profit,
   ao.supplier_cost_at_purchase AS supplier_cost_snapshot,
   ao.profit_credited,
   ao.queue_state
  FROM agent_orders ao
    LEFT JOIN agents a ON a.id = ao.agent_id;